name = "needforslotscasinoreview-net"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=needforslotscasinoreview.net"
HMAC_KEY = "9e2abd22b4bf726338428ea8e8eac8803a956a32875ce7d7fc93f582fde30be1"
COOKIE_NAME = "chj"
PLAY_PATH = "start-now"
BUTTON_ID = "pc87e0a6fd8059d1454307ceb5670e70d"
GATE_SALT = "cad0b6e39947c99d"
